type Product {
    id: ID!
    name: String!
    price: Float!
    stockQuantity: Int!
}

type Category {
    id: ID!
    name: String!
    description: String!
}

type Query {
    products: [Product!]!
    product(id: ID!): Product
    categories: [Category!]!
    category(id: ID!): Category!
}

type Mutation {
    createProduct(input: CreateProductInput!): Product!
    createCategory(input: CreateCategoryInput!): Category!
}

input CreateProductInput {
    name: String!
    description: String!
    price: Float!
    supplier_id: Int!
    category_id: Int!
}

input CreateCategoryInput {
    name: String!
    category: String!
}